In [1]:
import numpy as np
from PIL import Image

In [2]:
img = Image.open('jenna.jpg')
gray_img = img.convert('L')

In [3]:
np_array = np.array(gray_img)
print(np_array.shape)

(1242, 1242)


In [4]:
#gray_img

In [5]:
np_array

array([[45, 45, 45, ...,  6,  6,  6],
       [45, 45, 45, ...,  6,  6,  6],
       [45, 45, 45, ...,  6,  6,  6],
       ...,
       [ 5,  5,  5, ...,  3,  3,  3],
       [ 5,  6,  6, ...,  3,  3,  3],
       [ 5,  6,  6, ...,  3,  3,  3]], dtype=uint8)

In [6]:
kernel_1 = np.matrix([[0, 0, 0], [1, 1, 1], [0, 0, 0]])
kernel_2 = np.matrix([[0, 1, 0], [0, 1, 0], [0, 1, 0]])

In [7]:
kernel_1
kernel_2

matrix([[0, 1, 0],
        [0, 1, 0],
        [0, 1, 0]])

In [19]:
test_matrix = np.matrix([[1,2,3,44],[4,5,6,77],[7,8,9,0],[11,22,33,44]])

In [37]:
test_matrix = np.arange(16).reshape(4,4)

In [38]:
test_matrix[:2,:2]

array([[0, 1],
       [4, 5]])

In [39]:
test_kernel = np.arange(4).reshape(2,2)

In [40]:
test_kernel

array([[0, 1],
       [2, 3]])

In [ ]:
test_matrix[:2,:2]